version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=pachoalcohol
      - MYSQL_DATABASE=inventario
    ports:
      - "3306:3306"

  springboot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springboot
    ports:
      - "8080:8080"
    depends_on:
      - mysql
